[package]
name = "opendata-spiders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
# anyhow = "1.0.71"
async-trait = "0.1.68"
flate2 = "1.0.26"
quick-xml = { version = "0.28.2", features = ["serde", "serialize"] }
reqwest = { version = "0.11.17", features = [
    "rustls",
    "json",
    "rustls-tls",
    "brotli",
    "gzip",
], default-features = false }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread", "fs"] }
ulid = "1.0.0"
webcrawler = { version = "0.1.0", path = "../webcrawler" }
swegov-opendata = { version = "0.2.0", path = "../swegov-opendata" }
deserx = { git = "https://github.com/kod-kristoff/deserx", version = "0.1.0" }
anyhow = "1.0.71"
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
