[package]
name = "preprocess-rd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.cargo-machete]
ignored = ["exn"]

[[bin]]
doctest = false
name = "preprocess-rd"
test = false

[dependencies]
clap = { workspace = true, features = ["cargo", "derive"] }
exn.workspace = true
preprocess-ui = { workspace = true }
swegov-opendata-preprocess = { workspace = true }
