[package]
name = "xml2json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.28.2"
serde_json = "1.0.96"

[dev-dependencies]
error-iter = "0.4.1"
