[package]
name = "preprocess-sfs"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
doctest = false
name = "preprocess-sfs"
path = "src/bin/cli/main.rs"
test = false

[dependencies]
chrono.workspace = true
clap = { workspace = true, features = ["cargo", "derive"] }
exn.workspace = true
fs-err.workspace = true
miette.workspace = true
minidom-extension.workspace = true
once_cell.workspace = true
preprocess-progress.workspace = true
# local deps
preprocess-ui = { workspace = true }
regex.workspace = true
serde_json.workspace = true
sparv-extension.workspace = true
swegov-opendata.workspace = true
swegov-opendata-preprocess.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing_log_error.workspace = true

[dev-dependencies]
insta.workspace = true
pretty_assertions.workspace = true
